version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672" # AMQP
            - "15672:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

    payment-service:
        build:
            context: ./payment_service
        container_name: payment-service
        ports:
            - "8000:8000"
        environment:
            # (none needed for this simple mock)
            # if needed, add configs here
            PASS: "secret"
        depends_on:
            - rabbitmq

    order-service:
        build:
            context: ./order_service
        container_name: order-service
        ports:
            - "8001:8001"
        environment:
            PAYMENT_SERVICE_URL: http://payment-service:8000
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USER: user
            RABBITMQ_PASS: password
        depends_on:
            - payment-service
            - rabbitmq

    inventory-service:
        build:
            context: ./inventory_service
        container_name: inventory-service
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USER: user
            RABBITMQ_PASS: password
        depends_on:
            - rabbitmq
